In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random as rd
from sim import *
mimu = T20SimX(dir='upto2019\ArrandVersion.pkl')

In [2]:
mimu.p_i70j['RG Sharma']

array([3.14956100e-01, 4.27173250e-01, 5.54417970e-02, 1.71260894e-03,
       1.29407426e-01, 9.67918480e-06, 5.24651928e-02, 1.88339466e-02])

In [85]:
np.sum(mimu.p_i70j['RG Sharma']*mimu.Tau_owj[13,2,:]/np.sum(mimu.p_i70j['RG Sharma']*mimu.Tau_owj[13,2,:]) * np.array([0,1,2,3,4,5,6,0]))

1.3890495382647838

In [86]:
np.sum(mimu.p_i70j['RG Sharma']*mimu.Tau_owj[13,8,:]/np.sum(mimu.p_i70j['RG Sharma']*mimu.Tau_owj[13,8,:])* np.array([0,1,2,3,4,5,6,0]))

1.4649654997432267

In [87]:
np.sum(mimu.p_i70j['RG Sharma']*mimu.Tau_owj[19,2,:]/np.sum(mimu.p_i70j['RG Sharma']*mimu.Tau_owj[19,2,:]) * np.array([0,1,2,3,4,5,6,0]))

1.517017036425671

In [88]:
np.sum(mimu.p_i70j['RG Sharma']*mimu.Tau_owj[19,8,:]/np.sum(mimu.p_i70j['RG Sharma']*mimu.Tau_owj[19,8,:]) * np.array([0,1,2,3,4,5,6,0]))

1.5685440919245084

In [17]:
mimu.p_i70j['KD Karthik']

array([0.31449074, 0.4331135 , 0.06000196, 0.00599177, 0.13417607,
       0.00266038, 0.03205067, 0.01751491])

In [59]:
mimu.p_i70j['PP Chawla']

array([3.64808927e-01, 4.42431695e-01, 4.74325600e-02, 1.39604255e-03,
       1.18534665e-01, 9.45627689e-05, 1.24621954e-02, 1.28393525e-02])

In [56]:
mimu.p_i70j['CH Gayle']

array([3.68330509e-01, 3.32040269e-01, 3.12651535e-02, 3.20264572e-03,
       1.21472791e-01, 6.81584176e-06, 1.11932439e-01, 3.17493770e-02])

In [9]:
def erpb(bat):
    return np.sum(mimu.p_i70j[bat]*np.array([0,1,2,3,4,5,6,0]))

In [10]:
erpb('RG Sharma')

1.375663926906425

In [11]:
erpb('SL Malinga')

0.8503040616392072

In [16]:
erpb('CH Gayle')

1.56169839192399

In [60]:
erpb('PP Chawla')

1.0908695882885824